# Generated by Django 5.1 on 2024-08-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='remente',
            new_name='remetente',
        ),
    ]
