# Generated by Django 4.2.16 on 2024-09-18 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'permissions': (('pode_deletar', 'Permissão para deletar um cartão'), ('pode_atualizar', 'Permissão para atualizar um cartão'), ('pode_criar', 'Permissão para criar um cartão'))},
        ),
    ]
