# Generated by Django 4.2.16 on 2024-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cartao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
